In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
df = pd.read_csv("SC-63-Member.csv", encoding="utf-8")
cs_df = df[df.Major == "วิทยาการคอมพิวเตอร์"]

In [15]:
cs_df

,No,ID,Name,Branch,Major
721,1,633020032-4,นายกล้ายุทธ พิชัยเชิด,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
722,2,633020033-2,นายจิรภัทร ชื่นสกุล,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
723,3,633020034-0,นายชาญยุทธ ดงทะนา,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
724,4,633020035-8,นายชานน ภาคีนุยะ,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
725,5,633020036-6,นายณัฐนันท์ วรรณภา,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
...,...,...,...,...,...
825,105,633021006-0,นางสาวสุภาวดี มาวัน,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
826,106,633021007-8,นายอนุชา เงินขาว,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
827,107,633021008-6,นายอภิวัฒน์ แก้วกำ,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
828,108,633021009-4,นายอัครเดช วิทยาวุฒิรัตน์,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
829,109,633021010-9,นายอัษฎาวุธ หอมดี,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์

In [16]:
len(cs_df)

109

In [17]:
cs_df.to_csv("CS-63-Member.csv", index=False)

In [20]:
cs_df = pd.read_csv("CS-63-Member.csv")
cs_df

,No,ID,Name,Branch,Major
0,1,633020032-4,นายกล้ายุทธ พิชัยเชิด,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
1,2,633020033-2,นายจิรภัทร ชื่นสกุล,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
2,3,633020034-0,นายชาญยุทธ ดงทะนา,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
3,4,633020035-8,นายชานน ภาคีนุยะ,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
4,5,633020036-6,นายณัฐนันท์ วรรณภา,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
...,...,...,...,...,...
104,105,633021006-0,นางสาวสุภาวดี มาวัน,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
105,106,633021007-8,นายอนุชา เงินขาว,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
106,107,633021008-6,นายอภิวัฒน์ แก้วกำ,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
107,108,633021009-4,นายอัครเดช วิทยาวุฒิรัตน์,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์
108,109,633021010-9,นายอัษฎาวุธ หอมดี,วิทยาการคอมพิวเตอร์,วิทยาการคอมพิวเตอร์